import assert from "node:assert/strict";
import { readFile, writeFile } from "node:fs/promises";
const html = await readFile("consumers/neutral/dist/index.html", "utf8");
assert.match(html, /<title>Neutral publication<\/title>/);
assert.match(html, /data-publication="neutral"/);
assert.match(html, /lang="en"/);
assert.doesNotMatch(html, /invalid-override/);
assert.match(html, /href="https:\/\/neutral.example\/"/);
assert.match(html, /href="#main"/);
assert.match(html, /<main id="main" tabindex="-1">/);
assert.doesNotMatch(html, /<script\b/);
const receipt = { neutral: { htmlBytes: Buffer.byteLength(html) } };
await writeFile(".qualification-output.json", JSON.stringify(receipt, null, 2));
console.log("Neutral document output", JSON.stringify(receipt));
